#!/usr/bin/env python3
"""Scrape Swedish pharmacies for opening hours.

Usage:
  skrapa ALLA
  skrapa apoteksgruppen
  skrapa apoteket
  skrapa lloyds
  skrapa kronans
  skrapa hjartat
  skrapa soaf

Options:
  -h --help             Show this screen.
  -f --firefox-profile  Path to profile
  -o --output           Output directory
  -h --headless         Run Firefox headless

A set of scripts for retrieving opening hours from all the major pharmacy chains in Sweden.
Requires Firefox with the geckoengine driver, python 3.5 or later, and a API key for MapQuest.
Before running this program, you need to create text file called ".secrets"
in the same folder as this README document. The content should look like this:

[mapquest]
key = <your long api key here>

Then, you need to start Firefox and set it to block location requests.
"""

from docopt import docopt
import lib.scraper as sc
import os
import datetime




if __name__=="__main__":
    #options: firefox profile, output directory, headless,
    #arguments: pharmacy
    all_modules = {
        "apoteksgruppen":sc.ApoteksgruppenSpider,
        "apoteket":sc.ApoteketSpider,
        "lloyds":sc.LloydsSpider,
        "kronans":sc.KronansApotekSpider,
        "hjartat":sc.HjartatSpider,
        "soaf":sc.SOAFSpider
    }
    if selected_pharmacy=="ALLA":
        pharmacies = all_modules.keys()
    else:
        pharmacies = [selected_pharmacy]
    #scrape one or many pharmacy chain
    for current_pharmacy in pharmacies:
        if not os.path.isdir(output_directory):
            os.mkdir(output_directory)
        curr_module = all_modules[current_pharmacy]() #my_firefox_profile=False, quit_when_finished=True):
        curr_module.write_xlsx(
            os.path.join(
                output_directory,
                f"{current_pharmacy}_{datetime.now().isoformat().replace(':', '_')}.xlsx",
            )
        )